<?php
//Interact GET Started Sidebaron My Dashboard

/**
 * Implementation of hook_menu().
 */
function gsa_get_started_menu() {
  $items = array();
  $items['admin/config/get-started'] = array(
    'title' => 'GSA Get Started',
    'description' => 'Settings for Get Started Block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsa_get_started_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_block_info().
 */
function gsa_get_started_block_info() {
  $blocks['get_started']['info'] = t('Get Started Info');
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function gsa_get_started_block_view($delta = '') {
  switch ($delta) {
    case 'get_started':
      $block['subject'] = t('Get Started');
      $block['content'] = _gsa_get_started_block();
      break;
  }
  return $block;
}

/**
 * Administration settings
 */
function gsa_get_started_admin_settings() {
  $form = array();

  $form['gsa_get_started_node'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter node id of get started page'),
    '#description' => t('Specify the page id which is display on get started page'),
    '#default_value' => variable_get('gsa_get_started_node', ''),
  );
  return system_settings_form($form);
}

function _gsa_get_started_block() {
  global $user;

  if ($nid = variable_get('gsa_get_started_node', null)) {
    $node = node_load($nid);
    // render() needs a variable argument for pass-by-reference
    $node_view = node_view($node, 'teaser');
    $node_view['links']['#access'] = FALSE;
    $node_view['#gsa_hide_submitted'] = TRUE;
    $content = render($node_view);
    if (drupal_is_front_page() && $user->uid == 0) {
      $content .= '<div class="manual-button">' . l('Join the conversation today!', 'user') . '</div>';
    }
    else if (drupal_is_front_page() && $user->uid != 0) {
    	$content .= '<div class="manual-button">' . l('Join the conversation today!', 'dashboard') . '</div>';
    }
  }
  else{
    $content = null;
  }

  return  $content;
}	
