<?php

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function interact_ui_support_form_search_block_form_alter (&$form, &$form_state, $form_id){
  $form['search_block_form']['#default_value'] = t('Search');
  $form['search_block_form']['#attributes'] = array(
  'onfocus' => 'if(this.value==\'' .t("Search"). '\') this.value ="";',
  'onblur' =>  'if(this.value=="") this.value = \'' .t("Search"). '\';');
}

