<?php

/**
 * Implementation of hook_init().
 */
function gsa_social_init() {
  $module_path = drupal_get_path('module', 'gsa_social');

  drupal_add_js($module_path .'/fancybox/jquery.easing-1.3.pack.js', array('scope' => 'footer'));
  drupal_add_js($module_path .'/fancybox/jquery.mousewheel-3.0.4.pack.js', array('scope' => 'footer'));
  drupal_add_js($module_path .'/fancybox/jquery.fancybox-1.3.4.pack.js', array('scope' => 'footer'));
  drupal_add_js($module_path .'/gsa_social.js', array('scope' => 'footer'));
  
  drupal_add_css($module_path .'/fancybox/jquery.fancybox-1.3.4.css');
  drupal_add_css($module_path .'/gsa_social.css');
  
  $socialWidth = gsa_social_get_current_width();
    
  drupal_add_js(array('socialFrameWidth' => $socialWidth + 50), 'setting');
  
  global $gsa_social_include_header, $gsa_social_include_footer;
  $gsa_social_include_header = array();
  $gsa_social_include_footer = array();
  
}

/**
 * Implementation of hook_menu().
 */
function gsa_social_menu() {
  $items = array();
  
  $items['admin/config/gsa-social'] = array(
      'title' => 'GSA Social',
      'description' => "Configure Which social shares to be enabled.",
      'page callback' => 'gsa_social_config',
      'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
  );
  
  $items['social/%node'] = array(
      'title' => t('Social Links'),
      'description' => '',
      'page callback' => 'gsa_social_links_for_node',
      'page arguments' => array(1),
      'access callback' => true,
      'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function gsa_social_theme() {
  $theme = array();
  
  $theme['page-social'] = array(
      'path' => drupal_get_path('module', 'gsa_social'),
      'template' => 'page',
  );
  
  return $theme;
}

/**
 * Implementation of hook_page_alter().
 */
function gsa_social_page_alter(&$page) {
  global $gsa_social_include_header, $gsa_social_include_footer;
  
  if (arg(0) == 'social') {
    print '<link rel="stylesheet" href="'. base_path() . drupal_get_path('module', 'gsa_social') .'/gsa_social.css">';
    print render($gsa_social_include_header);
    print "<body class='social-page' style='width: ". gsa_social_get_current_width() ."px; overflow: hidden; height: 30px; margin: 5px auto 0;'>". render($page['content']) ."</body>";
    print render($gsa_social_include_footer);
    exit;
  }
  
  $page['page_top'] = (isset($page['page_top']) && is_array($page['page_top'])) ? $page['page_top'] : array();
  $page['page_top'] = array_merge($page['page_top'], $gsa_social_include_header);
  
  $page['page_bottom'] = (isset($page['page_bottom']) && is_array($page['page_bottom'])) ? $page['page_bottom'] : array();
  $page['page_bottom'] = array_merge($page['page_bottom'], $gsa_social_include_footer);
}

function gsa_social_config() {
  return drupal_get_form('gsa_social_config_form');
}

/**
 * Form builder for module configuration.
 */
function gsa_social_config_form() {
  $form = array();
  
  $social_options = array();
  
  $social_options['fb'] = t('Facebook Like');
  $social_options['tweet'] = t('Twitter');
  $social_options['gp'] = t('Google +');
  $social_options['ln'] = t('LinkedIn');
  $social_options['ymw'] = t('Yahoo My Web');
  $social_options['stumbleupon'] = t('Stumbleupon');
  $social_options['digg'] = t('Digg');
  $social_options['pinterest'] = t('Pinterest');
  $social_options['delicious'] = t('Delicious');
  $social_options['newsvine'] = t('Newsvine');
  $social_options['technorati'] = t('Technorati');
  
  $form['gsa_social_links'] = array(
      '#title' => t('Select Social networks to share on'),
      '#type' => 'checkboxes',
      '#default_value' => variable_get('gsa_social_links', array('fb', 'gp', 'tweet')),
      '#options' => $social_options,
  );
  
  $form['gsa_social_yahoo_app_id'] = array(
      '#title' => t('Application ID for Yahoo My Web'),
      '#type' => 'textfield',
      '#defaul_value' => variable_get('gsa_social_yahoo_app_id', ''),
  );
  
  return system_settings_form($form);
}

// to display share link in individual post
function gsa_social_node_view($node, $view_mode, $langcode) {
	if($node->nid >0) {
	    // to display share link in the following post type
		$post_type = array('blog', 'discussion', 'document', 'wiki');
		// if post view mode is full and satisfy the post type for the share link
		if($view_mode=="full" && in_array($node->type, $post_type)) {
			global $base_url;
			$path = $base_url . url('node/'. $node->nid);
			$share_button = "";
			//If this post has permission to share. It will return the share link if yes. 
			if(gsa_social_get_links_for_node($node->nid)!=""){
				$share_button =	"<div><ul class='post-sharethis'><li>".gsa_social_get_links_for_node($node->nid)."<div class='views-field-sharethis'>".sharethis_get_button_HTML(sharethis_get_options_array(), $path, $node->title)."</div></li></ul></div>";
				// appending the share link  below the post content
				$node->content['body'][0]['#markup'].= $share_button;
			}
		}
	}
}

function gsa_social_get_links_for_node($nid) {
	if(gsa_social_content_access_status($nid)){
		$link = '<a nid="'. $nid .'" class="gsa-social-share-button" href="#share-div-'. $nid .'">'. t('share') .'</a>';
	}else{
		$link = '';
	}
  	return $link;
}

/**
* Function to return og content access of a particular node
* 
* @param $nid
* 	The node id for which the og access to be determined
* @return
* 	TRUE if access granted otherwise FALSE
*/
function gsa_social_content_access_status($nid){
	$node_to_test = node_load($nid);
	//$group = og_context();
	$gid = (isset($node_to_test->group_audience[$node_to_test->language][0]['gid']) && $node_to_test->group_audience[$node_to_test->language][0]['gid']>0) ? $node_to_test->group_audience[$node_to_test->language][0]['gid'] : 0 ;
	$group = ($gid > 0) ? og_load($gid) : '';
	if(isset($group) && is_object($group)){
		$groupEntity = $group->getEntity();
		$group_access_status = $groupEntity->group_access[$groupEntity->language][0]['value'];
	}else{
		//If its not a group context return false
		return FALSE;
	}
	
	$node_access_id = $node_to_test->group_content_access[$node_to_test->language][0]['value'];
	switch($node_access_id){
		//Public Content access
		case 1:
			return TRUE;
			break;
		//Private Content access
		case 2:
			return FALSE;
			break;
		//Use group default-> inherit content access from parent group
		case 0:
			switch($group_access_status){
				//Public Group
				case 0:
					return TRUE;
					break;
				//Private Group
				case 1:
					return FALSE;
					break;
			}
			break;
	}
}




function gsa_social_links_for_node($node) {
  $node = node_load($nid);
  
  $social_links = array();
  foreach (variable_get('gsa_social_links', array('fb', 'gp', 'tweet')) AS $social) {
    if (!$social) continue;
    $node_url = url($node->path, array('absolute' => true));
    $social_links[] = array(
        'data' => gsa_social_get_share_button($social, $node_url, $node->title, $node->nid),
        'class' => array('gsa-social-li-'. $social),
    );
  }
  
  return "<div class='gsa-social-share-links'>" . theme('item_list', array('items' => $social_links, 'type' => 'ul')) ."</div>";
}


function gsa_social_get_share_button($social, $url, $title, $nid) {
  global $gsa_social_include_header, $gsa_social_include_footer;
  $return = '';
  $title = $title ? $title : drupal_get_title();
  switch($social) {
    case 'fb':
      $fbdata = <<<FBDATA
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = '//connect.facebook.net/en_US/all.js#xfbml=1';
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
FBDATA;

      $gsa_social_include_header['fb'] = array(
          '#weight' => -50,
          '#markup' => $fbdata,
      );
      
      $code = "<div class='fb-like' data-href='%s' data-send='false' data-layout='button_count' data-width='100' data-show-faces='false'></div>";
      $return = sprintf($code, $url);
      break;
      
    case 'tweet':
      $code = '
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="%s" data-text="%s">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if (!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      ';
      $return = sprintf($code, $url, $title);
      break;
      
    case 'gp':
      $gpdata = <<<GPDATA
      <script type="text/javascript">
      (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/plusone.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
      </script>
GPDATA;
      $gsa_social_include_footer['gp'] = array(
          '#weight' => -50,
          '#markup' => $gpdata,
      );
      
      $code = '<div class="g-plusone" data-size="medium" data-annotation="inline" data-width="120" data-href="%s"></div>';
      $return = sprintf($code, $url);
      break;
    case 'ln':
      $gsa_social_include_header['ln'] = array(
          '#weight' => -49,
          '#markup' => '<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>',
      );
      
      $return = <<<ln
      <script type="IN/Share" data-url="{$url}" data-counter="right"></script>
ln;
      break;
      
    case 'ymw':
      $yahoo_app_id = variable_get('gsa_social_yahoo_app_id', '');
      if (!$yahoo_app_id) return '';
      
      $ymwdata = <<<ymwdata
      <link rel="stylesheet" href="http://l.yimg.com/a/lib/addtoyahoo/addtoyahoo_1.0.2.css"/>
      <script src="http://l.yimg.com/a/lib/addtoyahoo/addtoyahoo_1.0.5.js"></script>
ymwdata;

      $gsa_social_include_header['ymw'] = array(
          '#weight' => -47,
          '#markup' => $ymwdata,
      );
      
      $return = <<<ymw
      <div id="add_button_{$nid}" class="addToYButton"></div>
      <script>
      var button{$nid} = new YAHOO.one.AddToYahoo({
        id:"add_button_{$nid}",
        intl:"en-US",
        typeToAdd: ["app","{$yahoo_app_id}"],
        dropdownNetworks: ["yCom","yMy"],
        newWindow: true
      });
      </script>
ymw;
      break;
    case 'stumbleupon':
      $stumbleupon = <<<stumbleupondata
      <script type="text/javascript">
      (function() {
        var li = document.createElement('script'); li.type = 'text/javascript'; li.async = true;
        li.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + '//platform.stumbleupon.com/1/widgets.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(li, s);
      })();
      </script>
stumbleupondata;
      
      $gsa_social_include_header['stumbleupon'] = array(
          '#weight' => 1,
          '#markup' => $stumbleupon,
      );
      
      $return = <<<stumbleupon
      <su:badge layout="1" location="{$url}"></su:badge>
stumbleupon;
      break;
    case 'digg':

      $gsa_social_include_footer['digg'] = array(
          '#weight' => -47,
          '#markup' => '<script src="http://widgets.digg.com/buttons.js"></script>',
      );
      
      $title = rawurlencode($title);
      $url = rawurlencode($url);
      
      $return = <<<digg
      <a class="DiggThisButton DiggCompact"
        href="http://digg.com/submit?url={$url}&amp;title={$title}"
        rel="nofollow external"
      ></a>
digg;
      
      break;
    case 'pinterest':
      $title = rawurlencode($title);
      $url = rawurlencode($url);
      
      $return  = <<<pinterest
      <a href="http://pinterest.com/pin/create/button/?url={$url}&media={$url}&description={$title}" class="pin-it-button" count-layout="none"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
pinterest;
      
      $gsa_social_include_footer['pinterest'] = array(
          '#weight' => -46,
          '#markup' => '<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>',
      );

      break;
    case 'delicious':
      $title = rawurlencode($title);
      $url = rawurlencode($url);
      
      $return = <<<delicious
      <a href="https://www.delicious.com/save" style="width: 10px; display: inline-block;"
        onclick="window.open('https://www.delicious.com/save?v=5&noui&jump=close&url={$url}&title={$title}', 'delicious','toolbar=no,width=550,height=550'); return false;">
        <img src="https://www.delicious.com/static/img/delicious.small.gif" height="10" width="10" alt="Delicious" />
      </a>
delicious;
      break;
    case 'newsvine':
      $title = rawurlencode($title);
      $url = rawurlencode($url);
      
      $return = <<<newsvine
      <a title="newsvine.com" href="javascript:void(0)" onclick="window.open('http://www.newsvine.com/_wine/save?popoff=1&u={$url}&h={$title}','newsvine','toolbar=no,width=590,height=600,resizable=yes,scrollbars=yes')"><img src="http://i.newsvine.com/_vine/images/identity/button_seednewsvine.gif" alt="" border="0" width="16" height="16" />Seed Newsvine</a>
newsvine;
      
      break;
    case 'technorati':
      $image = base_path() . drupal_get_path('module', 'gsa_social') . '/technorati.png';
      $return = <<<technorati
      <a target="_blank" href="http://technorati.com/faves?add={$url}"><img src="{$image}" alt="Add us to your technorati favorites" width="80" height="15" border="0" /></a>
technorati;
      break;
  }
  
  return $return;
}

function gsa_social_get_current_width() {
  $socials = variable_get('gsa_social_links', array('fb', 'gp', 'tweet'));
  
  $social_options['fb'] = 45;
  $social_options['tweet'] = 60;
  $social_options['gp'] = 32;
  $social_options['ln'] = 61;
  $social_options['ymw'] = 40;
  $social_options['stumbleupon'] = 75;
  $social_options['digg'] = 50;
  $social_options['pinterest'] = 43;
  $social_options['delicious'] = 12;
  $social_options['newsvine'] = 18;
  $social_options['technorati'] = 80;
  
  $socialWidth = 10;
  
  foreach ($socials AS $social => $enabled) {
    if (!$enabled || !isset($social_options[$social])) continue;
    $socialWidth += $social_options[$social] + 5;
  }
  
  return $socialWidth;
}

