<?php

include_once('gsa_notifications.features.inc');

/**
 * Implementation of hook_init()
 */
function gsa_notifications_init() {
  
}

/**
 * Implementation of hook_node_view()
 */
function gsa_notifications_node_view($node, $view_mode, $langcode) {
  // Set notification links to popup via modal
  automodal_add('ul.links li[class^=notifications] a', array('width' => 450));
}

/**
 * Replacement function for missing notifications_queue_send_intervals().
 */
function notifications_queue_send_intervals($account = NULL) {
  return array(
    // -1 => t('Never'),
    0 => t('Immediately'),
    3600 => t('Every hour'),
    43200 => t('Twice a day'),
    86400 => t('Daily'),
    604800 => t('Weekly'),  
  );
}